// --- KENESU'S BOX ---
const KENESU_BOX = [
    // --- UMAS ---
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Special Week (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Silence Suzuka (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Maruzensky (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Oguri Cap (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Oguri Cap (Christmas)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Gold Ship (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Vodka (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Daiwa Scarlet (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Taiki Shuttle (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Grass Wonder (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'El Condor Pasa (Original)', details: 'Potential Lvl 2' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Symboli Rudolf (Original)', details: 'Potential Lvl 4' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Air Groove (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Biwa Hayahide (Original)', details: 'Potential Lvl 2' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Mayano Top Gun (Original)', details: 'Potential Lvl 3' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Mejiro Ryan (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Agnes Tachyon (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Winning Ticket (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Sakura Bakushin O (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Super Creek (Original)', details: 'Potential Lvl 2' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Haru Urara (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Matikanefukukitaru (Original)', details: 'Potential Lvl 3' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Nice Nature (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'King Halo (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Fuji Kiseki (Original)', details: 'Potential Lvl 3' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Grass Wonder (Fantasy)', details: 'Potential Lvl 3' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'El Condor Pasa (Fantasy)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'T.M. Opera O (New Year)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Narita Brian (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Air Groove (Wedding)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Tamomo Cross (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Mayano Top Gun (Wedding)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Mihono Bourbon (Original)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Gold City (Festival)', details: 'Potential Lvl 1' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Haru Urara (New Year)', details: 'Potential Lvl 5' },
    { cat: 'Uma', rarity: '3★', stat: 'Uma', name: 'Meisho Doto (Original)', details: 'Potential Lvl 5' },

    // --- SUPPORT CARDS ---
    { cat: 'Support', rarity: 'SSR', stat: 'Guts', name: 'Special Week', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Special Week', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Silence Suzuka', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Silence Suzuka', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Silence Suzuka (Welfare)', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Tokai Teio', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Gold Ship', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Gold Ship', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Guts', name: 'Grass Wonder', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Mejiro McQueen', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'El Condor Pasa', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Narita Brian', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'Tamomo Cross', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Wisdom', name: 'Fine Motion', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Wisdom', name: 'Mihono Bourbon', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Guts', name: 'Yukino Bijin', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Rice Shower', details: '3LB (Lvl 45)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'Rice Shower', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Guts', name: 'Ines Fujin', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'Winning Ticket', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Wisdom', name: 'Air Shakur', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Sakura Bakushin O', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Super Creek', details: '2LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'Smart Falcon', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Tosen Jordan', details: '2LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Nishino Flower', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Guts', name: 'Haru Urara', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'Bamboo Memory', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Biko Pegasus', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Power', name: 'Marvelous Sunday', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Matikanefukukitaru', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Meisho Doto', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Wisdom', name: 'Mejiro Dober', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Guts', name: 'Matikanetannhauser', details: 'MLB (Lvl 50)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Twin Turbo', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Stamina', name: 'Satano Diamond', details: '0LB (Lvl 30)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Kitasan Black', details: '3LB (Lvl 45)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Friend', name: 'Tazuna Hayakawa', details: '1LB (Lvl 35)' },
    { cat: 'Support', rarity: 'SSR', stat: 'Friend', name: 'Riko Kashimoto', details: '2LB (Lvl 40)' },

    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Fuji Kiseki', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Daiwa Scarlet', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Hishi Amazon', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Guts', name: 'Air Groove', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Agnes Digital', details: '3LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SR', stat: 'Guts', name: 'Tamomo Cross', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Fine Motion', details: '0LB (Lvl 25)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Biwa Hayahide', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Stamina', name: 'Mayano Top Gun', details: '3LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SR', stat: 'Stamina', name: 'Manhattan Cafe', details: '0LB (Lvl 25)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Mihono Bourbon', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Mejiro Ryan', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Guts', name: 'Yukino Bijin', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Agnes Tachyon', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Inari One', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'SR', stat: 'Speed', name: 'Eishin Flash', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Guts', name: 'Seeking the Pearl', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Speed', name: 'Shinko Windy', details: '3LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SR', stat: 'Speed', name: 'Sweep Tosho', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Stamina', name: 'Zenno Rob Roy', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Stamina', name: 'Tosen Jordan', details: '3LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SR', stat: 'Speed', name: 'Narita Taishin', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Nishino Flower', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Marvelous Sunday', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Matikanefukukitaru', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Guts', name: 'Meisho Doto', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Mejiro Dober', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Guts', name: 'Nice Nature', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Nice Nature', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Speed', name: 'King Halo', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Ikuno Dictus', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Power', name: 'Daitaku Helios', details: 'MLB (Lvl 45)' },
    { cat: 'Support', rarity: 'SR', stat: 'Wisdom', name: 'Mejiro Ardan', details: '3LB (Lvl 40)' },
    { cat: 'Support', rarity: 'SR', stat: 'Friend', name: 'Aoi Kiryuin', details: 'MLB (Lvl 45)' },

    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Special Week', details: 'MLB (Lvl 5)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Silence Suzuka', details: 'MLB (Lvl 40)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Tokai Teio', details: 'MLB (Lvl 5)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Maruzensky', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Fuji Kiseki', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Oguri Cap', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Gold Ship', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Vodka', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Daiwa Scarlet', details: 'MLB (Lvl 40)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Taiki Shuttle', details: 'MLB (Lvl 40)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Grass Wonder', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Hishi Amazon', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Mejiro McQueen', details: 'MLB (Lvl 40)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'El Condor Pasa', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'T.M. Opera O', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Narita Brian', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Symboli Rudolf', details: 'MLB (Lvl 40)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Agnes Digital', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Seiun Sky', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Tamomo Cross', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Fine Motion', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Biwa Hayahide', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Mayano Top Gun', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Manhattan Cafe', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Mihono Bourbon', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Mejiro Ryan', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Hishi Akebono', details: '1LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Yukino Bijin', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Rice Shower', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Ines Fujin', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Agnes Tachyon', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Admire Vega', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Winning Ticket', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Air Shakur', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Eishin Flash', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Curren Chan', details: '2LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Kawakami Princess', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Gold City', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Sakura Bakushin O', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Seeking the Pearl', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Shinko Windy', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Sweep Tosho', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Super Creek', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Smart Falcon', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Zenno Rob Roy', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Tosen Jordan', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Nakayama Festa', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Narita Taishin', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Nishino Flower', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Haru Urara', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Bamboo Memory', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Biko Pegasus', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Marvelous Sunday', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Matikanefukukitaru', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Meisho Doto', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Mejiro Dober', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Nice Nature', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'King Halo', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Matikanetannhauser', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Ikuno Dictus', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Mejiro Palmer', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Daitaku Helios', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Twin Turbo', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Satano Diamond', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Speed', name: 'Kitasan Black', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Stamina', name: 'Sakura Chiyono O', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Guts', name: 'Sirius Symboli', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Wisdom', name: 'Mejiro Ardan', details: '0LB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Power', name: 'Yaeno Muteki', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Friend', name: 'Tazuna Hayakawa', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Friend', name: 'Aoi Kiryuin', details: 'MLB (Lvl 1)' },
    { cat: 'Support', rarity: 'R', stat: 'Friend', name: 'Riko Kashimoto', details: 'MLB (Lvl 40)' }
];

// --- EXAMPLE DUMMY BOX FOR Player ---
const PLAYER_BOX = [
    { cat: 'Uma', rarity: '4★', stat: 'Uma', name: 'Smart Falcon (Original)', details: 'Potential Lvl 5' },
    { cat: 'Support', rarity: 'SSR', stat: 'Speed', name: 'Kitasan Black', details: 'MLB (Lvl 50)' }
];


// --- MASTER DICTIONARY ---
// This hooks the data to the dropdown in your HTML
const ALL_TRAINER_BOXES = {
    "Kenesu": KENESU_BOX,
    "Player": PLAYER_BOX
};